version: '3.7'

services:
  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
    volumes:
      - ./db/:/var/lib/postgresql/data postgres
    ports:
      - 5432:5432

  adminer:
    image: adminer
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
    ports:
      - 2020:2020

  nodemon:
    image: quirinecker/discord-node-bot:latest
    restart: always
    volumes:
      - ./:/usr/src/app/
